// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Models;

#nullable disable

namespace School.Migrations
{
    [DbContext(typeof(StudentDBcontext))]
    [Migration("20240830122817_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("Varchar(12)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("Varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(80)")
                        .HasColumnName("StudentName");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("Varchar(5)");

                    b.HasKey("StudentId");

                    b.ToTable("StudentsDate");
                });
#pragma warning restore 612, 618
        }
    }
}
